platform_info = {
    # Used by raw2proc
    'id' : 'mini_andi',
    'config_start_date' : '2010-04-01 00:00:00',
    'config_end_date' : '2010-07-31 00:00:00', # None or yyyy-mm-dd HH:MM:SS
    'packages' : ('system',
                  'turbidity',
                  'optode_127',
                  'optode_167',
                  'optode_169',
                  'optode_170',
                  'optode_171',
                  'optode_172',
                  'optode_173',
                  'optode_175',
                  'optode_176',
                  'optode_178',
                  'optode_179',
                  'conductivity',
                  'pressure',
                  'current',
                 ),
    # Required
    'institution' : 'Unversity of North Carolina at Chapel Hill (UNC-CH)',
    'institution_url' : 'http://www.unc.edu',
    'institution_dods_url' : 'http://whewell.marine.unc.edu/dods',
    'contact' : 'Howard Mendlovitz (mendlovitz@unc.edu)',
    'conventions' : 'CF-1.0; SEACOOS-CDL-v2.0',
    # Required by Scout
    'format_category_code' : 'fixed-point',
    'institution_code' : 'nccoos',
    # Required by Version Tracking
    'format' : 'seacoos_rt',
    'seacoos_rt_version' : '2.0',
    # Recommended
    'source' : 'Spongenet platform',
    'references' : 'http://ncccoos.org',
    'metadata_url' : 'http://whewell.marine.unc.edu/dods',
    'project' : 'UNC-CH Department of Marine Sciences',
    'project_url' : 'http://www.marine.unc.edu',
    # Custom
    'id_number' : '4887-231',
    'description' : 'Platform',
    'serial_number' : '231',
    'product_number' : '4887',
    'product_name' : 'Seaguard Datalogger IW',
    'type' : 'Instrument',
    'protocol_version' : '4',
    'xmlns' : 'http://www.aadi.no/RTOutSchema',
    'location' : 'NURC',
    'vertical_position': '0',
    'owner' : 'UNC Chapel Hill',
    'status_map' : '0:OK',
}
sensor_info = {
    'system' : { 'id' : 'system',
        # Used by raw2proc
        'raw_dir' : '/seacoos/data/nccoos/level0/'
        'largo/mini_andi/xml',
        'raw_file_glob' : '*.xml',
        'proc_dir' : '/seacoos/data/nccoos/level1/'
        'largo/mini_andi/nc',
        'process_module' : 'proc_mini_andi_system',
        'utc_offset' : 0,  # hours offset to utc
        'location' : 'Florida Keys National Marine Sanctuary',
        'lat' : 24.9500,   # degrees true (-) south, (+) north
        'lon' : -80.4536,  # degrees true (-) west, (+) east
        'mvar' : -5.6333,  # degrees (-) west, (+) east
        'elevation' : -20.0, # meters
        # Custom
        'id_number' : 'SN100-0',
        'serial_number' : '0',
        'product_number' : 'SN100',
        'product_name' : 'System Node',
        'description' : 'System Parameters',
        'adr' : '-4',
        'protocol_version' : '3',
        'vertical_position' : '0',
        'status_map' : '0:OK',
        # Custom for variables
        'voltage_id' : '0',
        'voltage_description' : 'Battery Voltage',
        'voltage_type' : 'VT_R4',
        'voltage_format' : '',
        'voltage_units' : 'V',
        'voltage_range_min' :'0',
        'voltage_range_max' : '15',
        'memory_id' : '1',
        'memory_description' : 'Memory Used',
        'memory_type' : 'VT_I4',
        'memory_format' : '',
        'memory_units' : 'Bytes',
        'memory_range_min' : '0',
        'memory_range_max' : '14024704',
        'interval_id' : '2',
        'interval_description' : 'Interval',
        'interval_type' : 'VT_I4',
        'interval_format' : '',
        'interval_units' : 'ms',
        'interval_range_min' : '',
        'interval_range_max' : '',
    },
    'turbidity' : { 'id' : 'turbidity',
        # Used by raw2proc
        'raw_dir' : '/seacoos/data/nccoos/level0/'
        'largo/mini_andi/xml',
        'raw_file_glob' : '*.xml',
        'proc_dir' : '/seacoos/data/nccoos/level1/'
        'largo/mini_andi/nc',
        'process_module' : 'proc_mini_andi_turbidity',
        'utc_offset' : 0,  # hours offset to utc
        'location' : 'Florida Keys National Marine Sanctuary',
        'lat' : 24.9500,   # degrees true (-) south, (+) north
        'lon' : -80.4536,  # degrees true (-) west, (+) east
        'mvar' : -5.6333,  # degrees (-) west, (+) east
        'elevation' : -20.0, # meters
        # Custom
        'id_number' : 'AN100-0',
        'serial_number' : '0',
        'product_number' : 'AN100',
        'product_name' : 'Analog Sensors',
        'description' : 'Turbidity #11692',
        'adr' : '-3',
        'protocol_version' : '3',
        'vertical_position' : '0',
        'status_map' : '0:OK',
        # Custom for variables
        'turbidity_id' : '3',
        'turbidity_description' : 'Turbidity',
        'turbidity_type' : 'VT_R8',
        'turbidity_format' : '',
        'turbidity_units' : 'FTU',
        'turbidity_range_min' :'0',
        'turbidity_range_max' : '125',
    },
    'optode_127' : { 'id' : 'optode_127',
        # Used by raw2proc
        'raw_dir' : '/seacoos/data/nccoos/level0/'
        'largo/mini_andi/xml',
        'raw_file_glob' : '*.xml',
        'proc_dir' : '/seacoos/data/nccoos/level1/'
        'largo/mini_andi/nc',
        'process_module' : 'proc_mini_andi_optode',
        'utc_offset' : 0,  # hours offset to utc
        'location' : 'Florida Keys National Marine Sanctuary',
        'lat' : 24.9500,   # degrees true (-) south, (+) north
        'lon' : -80.4536,  # degrees true (-) west, (+) east
        'mvar' : -5.6333,  # degrees (-) west, (+) east
        'elevation' : -20.0, # meters
        # Custom
        'id_number' : '4330F-127',
        'serial_number' : '127',
        'product_number' : '4330F',
        'product_name' : 'Optode Sensor',
        'description' : 'Optode Sensor 4330F#127',
        'adr' : '340736',
        'protocol_version' : '1',
        'vertical_position' : '0',
        'status_map' : '0:OK',
        # Custom for variables
        'o2concentration_id' : '0',
        'o2concentration_description' : 'O2Concentration',
        'o2concentration_type' : 'VT_R4',
        'o2concentration_format' : '%0.3f',
        'o2concentration_units' : 'uM',
        'o2concentration_range_min' :'0',
        'o2concentration_range_max' : '500',
        'airsaturation_id' : '1',
        'airsaturation_description' : 'AirSaturation',
        'airsaturation_type' : 'VT_R4',
        'airsaturation_format' : '%0.3f',
        'airsaturation_units' : '%',
        'airsaturation_range_min' :'0',
        'airsaturation_range_max' : '150',
        'temperature_id' : '2',
        'temperature_description' : 'Temperature',
        'temperature_type' : 'VT_R4',
        'temperature_format' : '%0.3f',
        'temperature_units' : 'Deg.C',
        'temperature_range_min' :'0',
        'temperature_range_max' : '40',
        'calphase_id' : '3',
        'calphase_description' : 'CalPhase',
        'calphase_type' : 'VT_R4',
        'calphase_format' : '%0.3f',
        'calphase_units' : 'Deg',
        'calphase_range_min' :'0',
        'calphase_range_max' : '90',
        'tcphase_id' : '4',
        'tcphase_description' : 'TCPhase',
        'tcphase_type' : 'VT_R4',
        'tcphase_format' : '%0.3f',
        'tcphase_units' : 'Deg',
        'tcphase_range_min' :'0',
        'tcphase_range_max' : '90',
        'c1rph_id' : '5',
        'c1rph_description' : 'C1RPh',
        'c1rph_type' : 'VT_R4',
        'c1rph_format' : '%0.3f',
        'c1rph_units' : 'Deg',
        'c1rph_range_min' :'0',
        'c1rph_range_max' : '90',
        'c2rph_id' : '6',
        'c2rph_description' : 'C2RPh',
        'c2rph_type' : 'VT_R4',
        'c2rph_format' : '%0.3f',
        'c2rph_units' : 'Deg',
        'c2rph_range_min' :'0',
        'c2rph_range_max' : '90',
        'c1amp_id' : '7',
        'c1amp_description' : 'C1Amp',
        'c1amp_type' : 'VT_R4',
        'c1amp_format' : '%0.1f',
        'c1amp_units' : 'mV',
        'c1amp_range_min' :'0',
        'c1amp_range_max' : '3300',
        'c2amp_id' : '8',
        'c2amp_description' : 'C2Amp',
        'c2amp_type' : 'VT_R4',
        'c2amp_format' : '%0.1f',
        'c2amp_units' : 'mV',
        'c2amp_range_min' :'0',
        'c2amp_range_max' : '3300',
        'rawtemp_id' : '9',
        'rawtemp_description' : 'RawTemp',
        'rawtemp_type' : 'VT_R4',
        'rawtemp_format' : '%0.1f',
        'rawtemp_units' : 'mV',
        'rawtemp_range_min' :'0',
        'rawtemp_range_max' : '1500',
    },
    'optode_167' : { 'id' : 'optode_167',
        # Used by raw2proc
        'raw_dir' : '/seacoos/data/nccoos/level0/'
        'largo/mini_andi/xml',
        'raw_file_glob' : '*.xml',
        'proc_dir' : '/seacoos/data/nccoos/level1/'
        'largo/mini_andi/nc',
        'process_module' : 'proc_mini_andi_optode',
        'utc_offset' : 0,  # hours offset to utc
        'location' : 'Florida Keys National Marine Sanctuary',
        'lat' : 24.9500,   # degrees true (-) south, (+) north
        'lon' : -80.4536,  # degrees true (-) west, (+) east
        'mvar' : -5.6333,  # degrees (-) west, (+) east
        'elevation' : -20.0, # meters
        # Custom
        'id_number' : '4330F-167',
        'serial_number' : '167',
        'product_number' : '4330F',
        'product_name' : 'Optode Sensor',
        'description' : 'Optode Sensor 4330F#167',
        'adr' : '352512',
        'protocol_version' : '1',
        'vertical_position' : '0',
        'status_map' : '0:OK',
        # Custom for variables
        'o2concentration_id' : '0',
        'o2concentration_description' : 'O2Concentration',
        'o2concentration_type' : 'VT_R4',
        'o2concentration_format' : '%0.3f',
        'o2concentration_units' : 'uM',
        'o2concentration_range_min' :'0',
        'o2concentration_range_max' : '500',
        'airsaturation_id' : '1',
        'airsaturation_description' : 'AirSaturation',
        'airsaturation_type' : 'VT_R4',
        'airsaturation_format' : '%0.3f',
        'airsaturation_units' : '%',
        'airsaturation_range_min' :'0',
        'airsaturation_range_max' : '150',
        'temperature_id' : '2',
        'temperature_description' : 'Temperature',
        'temperature_type' : 'VT_R4',
        'temperature_format' : '%0.3f',
        'temperature_units' : 'Deg.C',
        'temperature_range_min' :'0',
        'temperature_range_max' : '40',
        'calphase_id' : '3',
        'calphase_description' : 'CalPhase',
        'calphase_type' : 'VT_R4',
        'calphase_format' : '%0.3f',
        'calphase_units' : 'Deg',
        'calphase_range_min' :'0',
        'calphase_range_max' : '90',
        'tcphase_id' : '4',
        'tcphase_description' : 'TCPhase',
        'tcphase_type' : 'VT_R4',
        'tcphase_format' : '%0.3f',
        'tcphase_units' : 'Deg',
        'tcphase_range_min' :'0',
        'tcphase_range_max' : '90',
        'c1rph_id' : '5',
        'c1rph_description' : 'C1RPh',
        'c1rph_type' : 'VT_R4',
        'c1rph_format' : '%0.3f',
        'c1rph_units' : 'Deg',
        'c1rph_range_min' :'0',
        'c1rph_range_max' : '90',
        'c2rph_id' : '6',
        'c2rph_description' : 'C2RPh',
        'c2rph_type' : 'VT_R4',
        'c2rph_format' : '%0.3f',
        'c2rph_units' : 'Deg',
        'c2rph_range_min' :'0',
        'c2rph_range_max' : '90',
        'c1amp_id' : '7',
        'c1amp_description' : 'C1Amp',
        'c1amp_type' : 'VT_R4',
        'c1amp_format' : '%0.1f',
        'c1amp_units' : 'mV',
        'c1amp_range_min' :'0',
        'c1amp_range_max' : '3300',
        'c2amp_id' : '8',
        'c2amp_description' : 'C2Amp',
        'c2amp_type' : 'VT_R4',
        'c2amp_format' : '%0.1f',
        'c2amp_units' : 'mV',
        'c2amp_range_min' :'0',
        'c2amp_range_max' : '3300',
        'rawtemp_id' : '9',
        'rawtemp_description' : 'RawTemp',
        'rawtemp_type' : 'VT_R4',
        'rawtemp_format' : '%0.1f',
        'rawtemp_units' : 'mV',
        'rawtemp_range_min' :'0',
        'rawtemp_range_max' : '1500',
    },
    'optode_169' : { 'id' : 'optode_169',
        # Used by raw2proc
        'raw_dir' : '/seacoos/data/nccoos/level0/'
        'largo/mini_andi/xml',
        'raw_file_glob' : '*.xml',
        'proc_dir' : '/seacoos/data/nccoos/level1/'
        'largo/mini_andi/nc',
        'process_module' : 'proc_mini_andi_optode',
        'utc_offset' : 0,  # hours offset to utc
        'location' : 'Florida Keys National Marine Sanctuary',
        'lat' : 24.9500,   # degrees true (-) south, (+) north
        'lon' : -80.4536,  # degrees true (-) west, (+) east
        'mvar' : -5.6333,  # degrees (-) west, (+) east
        'elevation' : -20.0, # meters
        # Custom
        'id_number' : '4330F-169',
        'serial_number' : '169',
        'product_number' : '4330F',
        'product_name' : 'Optode Sensor',
        'description' : 'Optode Sensor 4330F#169',
        'adr' : '353024',
        'protocol_version' : '1',
        'vertical_position' : '0',
        'status_map' : '0:OK',
        # Custom for variables
        'o2concentration_id' : '0',
        'o2concentration_description' : 'O2Concentration',
        'o2concentration_type' : 'VT_R4',
        'o2concentration_format' : '%0.3f',
        'o2concentration_units' : 'uM',
        'o2concentration_range_min' :'0',
        'o2concentration_range_max' : '500',
        'airsaturation_id' : '1',
        'airsaturation_description' : 'AirSaturation',
        'airsaturation_type' : 'VT_R4',
        'airsaturation_format' : '%0.3f',
        'airsaturation_units' : '%',
        'airsaturation_range_min' :'0',
        'airsaturation_range_max' : '150',
        'temperature_id' : '2',
        'temperature_description' : 'Temperature',
        'temperature_type' : 'VT_R4',
        'temperature_format' : '%0.3f',
        'temperature_units' : 'Deg.C',
        'temperature_range_min' :'0',
        'temperature_range_max' : '40',
        'calphase_id' : '3',
        'calphase_description' : 'CalPhase',
        'calphase_type' : 'VT_R4',
        'calphase_format' : '%0.3f',
        'calphase_units' : 'Deg',
        'calphase_range_min' :'0',
        'calphase_range_max' : '90',
        'tcphase_id' : '4',
        'tcphase_description' : 'TCPhase',
        'tcphase_type' : 'VT_R4',
        'tcphase_format' : '%0.3f',
        'tcphase_units' : 'Deg',
        'tcphase_range_min' :'0',
        'tcphase_range_max' : '90',
        'c1rph_id' : '5',
        'c1rph_description' : 'C1RPh',
        'c1rph_type' : 'VT_R4',
        'c1rph_format' : '%0.3f',
        'c1rph_units' : 'Deg',
        'c1rph_range_min' :'0',
        'c1rph_range_max' : '90',
        'c2rph_id' : '6',
        'c2rph_description' : 'C2RPh',
        'c2rph_type' : 'VT_R4',
        'c2rph_format' : '%0.3f',
        'c2rph_units' : 'Deg',
        'c2rph_range_min' :'0',
        'c2rph_range_max' : '90',
        'c1amp_id' : '7',
        'c1amp_description' : 'C1Amp',
        'c1amp_type' : 'VT_R4',
        'c1amp_format' : '%0.1f',
        'c1amp_units' : 'mV',
        'c1amp_range_min' :'0',
        'c1amp_range_max' : '3300',
        'c2amp_id' : '8',
        'c2amp_description' : 'C2Amp',
        'c2amp_type' : 'VT_R4',
        'c2amp_format' : '%0.1f',
        'c2amp_units' : 'mV',
        'c2amp_range_min' :'0',
        'c2amp_range_max' : '3300',
        'rawtemp_id' : '9',
        'rawtemp_description' : 'RawTemp',
        'rawtemp_type' : 'VT_R4',
        'rawtemp_format' : '%0.1f',
        'rawtemp_units' : 'mV',
        'rawtemp_range_min' :'0',
        'rawtemp_range_max' : '1500',
    },
    'optode_170' : { 'id' : 'optode_170',
        # Used by raw2proc
        'raw_dir' : '/seacoos/data/nccoos/level0/'
        'largo/mini_andi/xml',
        'raw_file_glob' : '*.xml',
        'proc_dir' : '/seacoos/data/nccoos/level1/'
        'largo/mini_andi/nc',
        'process_module' : 'proc_mini_andi_optode',
        'utc_offset' : 0,  # hours offset to utc
        'location' : 'Florida Keys National Marine Sanctuary',
        'lat' : 24.9500,   # degrees true (-) south, (+) north
        'lon' : -80.4536,  # degrees true (-) west, (+) east
        'mvar' : -5.6333,  # degrees (-) west, (+) east
        'elevation' : -20.0, # meters
        # Custom
        'id_number' : '4330F-170',
        'serial_number' : '170',
        'product_number' : '4330F',
        'product_name' : 'Optode Sensor',
        'description' : 'Optode Sensor 4330F#170',
        'adr' : '353280',
        'protocol_version' : '1',
        'vertical_position' : '0',
        'status_map' : '0:OK',
        # Custom for variables
        'o2concentration_id' : '0',
        'o2concentration_description' : 'O2Concentration',
        'o2concentration_type' : 'VT_R4',
        'o2concentration_format' : '%0.3f',
        'o2concentration_units' : 'uM',
        'o2concentration_range_min' :'0',
        'o2concentration_range_max' : '500',
        'airsaturation_id' : '1',
        'airsaturation_description' : 'AirSaturation',
        'airsaturation_type' : 'VT_R4',
        'airsaturation_format' : '%0.3f',
        'airsaturation_units' : '%',
        'airsaturation_range_min' :'0',
        'airsaturation_range_max' : '150',
        'temperature_id' : '2',
        'temperature_description' : 'Temperature',
        'temperature_type' : 'VT_R4',
        'temperature_format' : '%0.3f',
        'temperature_units' : 'Deg.C',
        'temperature_range_min' :'0',
        'temperature_range_max' : '40',
        'calphase_id' : '3',
        'calphase_description' : 'CalPhase',
        'calphase_type' : 'VT_R4',
        'calphase_format' : '%0.3f',
        'calphase_units' : 'Deg',
        'calphase_range_min' :'0',
        'calphase_range_max' : '90',
        'tcphase_id' : '4',
        'tcphase_description' : 'TCPhase',
        'tcphase_type' : 'VT_R4',
        'tcphase_format' : '%0.3f',
        'tcphase_units' : 'Deg',
        'tcphase_range_min' :'0',
        'tcphase_range_max' : '90',
        'c1rph_id' : '5',
        'c1rph_description' : 'C1RPh',
        'c1rph_type' : 'VT_R4',
        'c1rph_format' : '%0.3f',
        'c1rph_units' : 'Deg',
        'c1rph_range_min' :'0',
        'c1rph_range_max' : '90',
        'c2rph_id' : '6',
        'c2rph_description' : 'C2RPh',
        'c2rph_type' : 'VT_R4',
        'c2rph_format' : '%0.3f',
        'c2rph_units' : 'Deg',
        'c2rph_range_min' :'0',
        'c2rph_range_max' : '90',
        'c1amp_id' : '7',
        'c1amp_description' : 'C1Amp',
        'c1amp_type' : 'VT_R4',
        'c1amp_format' : '%0.1f',
        'c1amp_units' : 'mV',
        'c1amp_range_min' :'0',
        'c1amp_range_max' : '3300',
        'c2amp_id' : '8',
        'c2amp_description' : 'C2Amp',
        'c2amp_type' : 'VT_R4',
        'c2amp_format' : '%0.1f',
        'c2amp_units' : 'mV',
        'c2amp_range_min' :'0',
        'c2amp_range_max' : '3300',
        'rawtemp_id' : '9',
        'rawtemp_description' : 'RawTemp',
        'rawtemp_type' : 'VT_R4',
        'rawtemp_format' : '%0.1f',
        'rawtemp_units' : 'mV',
        'rawtemp_range_min' :'0',
        'rawtemp_range_max' : '1500',
    },
    'optode_171' : { 'id' : 'optode_171',
        # Used by raw2proc
        'raw_dir' : '/seacoos/data/nccoos/level0/'
        'largo/mini_andi/xml',
        'raw_file_glob' : '*.xml',
        'proc_dir' : '/seacoos/data/nccoos/level1/'
        'largo/mini_andi/nc',
        'process_module' : 'proc_mini_andi_optode',
        'utc_offset' : 0,  # hours offset to utc
        'location' : 'Florida Keys National Marine Sanctuary',
        'lat' : 24.9500,   # degrees true (-) south, (+) north
        'lon' : -80.4536,  # degrees true (-) west, (+) east
        'mvar' : -5.6333,  # degrees (-) west, (+) east
        'elevation' : -20.0, # meters
        # Custom
        'id_number' : '4330F-171',
        'serial_number' : '171',
        'product_number' : '4330F',
        'product_name' : 'Optode Sensor',
        'description' : 'Optode Sensor 4330F#171',
        'adr' : '353536',
        'protocol_version' : '1',
        'vertical_position' : '0',
        'status_map' : '0:OK',
        # Custom for variables
        'o2concentration_id' : '0',
        'o2concentration_description' : 'O2Concentration',
        'o2concentration_type' : 'VT_R4',
        'o2concentration_format' : '%0.3f',
        'o2concentration_units' : 'uM',
        'o2concentration_range_min' :'0',
        'o2concentration_range_max' : '500',
        'airsaturation_id' : '1',
        'airsaturation_description' : 'AirSaturation',
        'airsaturation_type' : 'VT_R4',
        'airsaturation_format' : '%0.3f',
        'airsaturation_units' : '%',
        'airsaturation_range_min' :'0',
        'airsaturation_range_max' : '150',
        'temperature_id' : '2',
        'temperature_description' : 'Temperature',
        'temperature_type' : 'VT_R4',
        'temperature_format' : '%0.3f',
        'temperature_units' : 'Deg.C',
        'temperature_range_min' :'0',
        'temperature_range_max' : '40',
        'calphase_id' : '3',
        'calphase_description' : 'CalPhase',
        'calphase_type' : 'VT_R4',
        'calphase_format' : '%0.3f',
        'calphase_units' : 'Deg',
        'calphase_range_min' :'0',
        'calphase_range_max' : '90',
        'tcphase_id' : '4',
        'tcphase_description' : 'TCPhase',
        'tcphase_type' : 'VT_R4',
        'tcphase_format' : '%0.3f',
        'tcphase_units' : 'Deg',
        'tcphase_range_min' :'0',
        'tcphase_range_max' : '90',
        'c1rph_id' : '5',
        'c1rph_description' : 'C1RPh',
        'c1rph_type' : 'VT_R4',
        'c1rph_format' : '%0.3f',
        'c1rph_units' : 'Deg',
        'c1rph_range_min' :'0',
        'c1rph_range_max' : '90',
        'c2rph_id' : '6',
        'c2rph_description' : 'C2RPh',
        'c2rph_type' : 'VT_R4',
        'c2rph_format' : '%0.3f',
        'c2rph_units' : 'Deg',
        'c2rph_range_min' :'0',
        'c2rph_range_max' : '90',
        'c1amp_id' : '7',
        'c1amp_description' : 'C1Amp',
        'c1amp_type' : 'VT_R4',
        'c1amp_format' : '%0.1f',
        'c1amp_units' : 'mV',
        'c1amp_range_min' :'0',
        'c1amp_range_max' : '3300',
        'c2amp_id' : '8',
        'c2amp_description' : 'C2Amp',
        'c2amp_type' : 'VT_R4',
        'c2amp_format' : '%0.1f',
        'c2amp_units' : 'mV',
        'c2amp_range_min' :'0',
        'c2amp_range_max' : '3300',
        'rawtemp_id' : '9',
        'rawtemp_description' : 'RawTemp',
        'rawtemp_type' : 'VT_R4',
        'rawtemp_format' : '%0.1f',
        'rawtemp_units' : 'mV',
        'rawtemp_range_min' :'0',
        'rawtemp_range_max' : '1500',
    },
    'optode_172' : { 'id' : 'optode_172',
        # Used by raw2proc
        'raw_dir' : '/seacoos/data/nccoos/level0/'
        'largo/mini_andi/xml',
        'raw_file_glob' : '*.xml',
        'proc_dir' : '/seacoos/data/nccoos/level1/'
        'largo/mini_andi/nc',
        'process_module' : 'proc_mini_andi_optode',
        'utc_offset' : 0,  # hours offset to utc
        'location' : 'Florida Keys National Marine Sanctuary',
        'lat' : 24.9500,   # degrees true (-) south, (+) north
        'lon' : -80.4536,  # degrees true (-) west, (+) east
        'mvar' : -5.6333,  # degrees (-) west, (+) east
        'elevation' : -20.0, # meters
        # Custom
        'id_number' : '4330F-172',
        'serial_number' : '172',
        'product_number' : '4330F',
        'product_name' : 'Optode Sensor',
        'description' : 'Optode Sensor 4330F#172',
        'adr' : '353792',
        'protocol_version' : '1',
        'vertical_position' : '0',
        'status_map' : '0:OK',
        # Custom for variables
        'o2concentration_id' : '0',
        'o2concentration_description' : 'O2Concentration',
        'o2concentration_type' : 'VT_R4',
        'o2concentration_format' : '%0.3f',
        'o2concentration_units' : 'uM',
        'o2concentration_range_min' :'0',
        'o2concentration_range_max' : '500',
        'airsaturation_id' : '1',
        'airsaturation_description' : 'AirSaturation',
        'airsaturation_type' : 'VT_R4',
        'airsaturation_format' : '%0.3f',
        'airsaturation_units' : '%',
        'airsaturation_range_min' :'0',
        'airsaturation_range_max' : '150',
        'temperature_id' : '2',
        'temperature_description' : 'Temperature',
        'temperature_type' : 'VT_R4',
        'temperature_format' : '%0.3f',
        'temperature_units' : 'Deg.C',
        'temperature_range_min' :'0',
        'temperature_range_max' : '40',
        'calphase_id' : '3',
        'calphase_description' : 'CalPhase',
        'calphase_type' : 'VT_R4',
        'calphase_format' : '%0.3f',
        'calphase_units' : 'Deg',
        'calphase_range_min' :'0',
        'calphase_range_max' : '90',
        'tcphase_id' : '4',
        'tcphase_description' : 'TCPhase',
        'tcphase_type' : 'VT_R4',
        'tcphase_format' : '%0.3f',
        'tcphase_units' : 'Deg',
        'tcphase_range_min' :'0',
        'tcphase_range_max' : '90',
        'c1rph_id' : '5',
        'c1rph_description' : 'C1RPh',
        'c1rph_type' : 'VT_R4',
        'c1rph_format' : '%0.3f',
        'c1rph_units' : 'Deg',
        'c1rph_range_min' :'0',
        'c1rph_range_max' : '90',
        'c2rph_id' : '6',
        'c2rph_description' : 'C2RPh',
        'c2rph_type' : 'VT_R4',
        'c2rph_format' : '%0.3f',
        'c2rph_units' : 'Deg',
        'c2rph_range_min' :'0',
        'c2rph_range_max' : '90',
        'c1amp_id' : '7',
        'c1amp_description' : 'C1Amp',
        'c1amp_type' : 'VT_R4',
        'c1amp_format' : '%0.1f',
        'c1amp_units' : 'mV',
        'c1amp_range_min' :'0',
        'c1amp_range_max' : '3300',
        'c2amp_id' : '8',
        'c2amp_description' : 'C2Amp',
        'c2amp_type' : 'VT_R4',
        'c2amp_format' : '%0.1f',
        'c2amp_units' : 'mV',
        'c2amp_range_min' :'0',
        'c2amp_range_max' : '3300',
        'rawtemp_id' : '9',
        'rawtemp_description' : 'RawTemp',
        'rawtemp_type' : 'VT_R4',
        'rawtemp_format' : '%0.1f',
        'rawtemp_units' : 'mV',
        'rawtemp_range_min' :'0',
        'rawtemp_range_max' : '1500',
    },
    'optode_173' : { 'id' : 'optode_173',
        # Used by raw2proc
        'raw_dir' : '/seacoos/data/nccoos/level0/'
        'largo/mini_andi/xml',
        'raw_file_glob' : '*.xml',
        'proc_dir' : '/seacoos/data/nccoos/level1/'
        'largo/mini_andi/nc',
        'process_module' : 'proc_mini_andi_optode',
        'utc_offset' : 0,  # hours offset to utc
        'location' : 'Florida Keys National Marine Sanctuary',
        'lat' : 24.9500,   # degrees true (-) south, (+) north
        'lon' : -80.4536,  # degrees true (-) west, (+) east
        'mvar' : -5.6333,  # degrees (-) west, (+) east
        'elevation' : -20.0, # meters
        # Custom
        'id_number' : '4330F-173',
        'serial_number' : '173',
        'product_number' : '4330F',
        'product_name' : 'Optode Sensor',
        'description' : 'Optode Sensor 4330F#173',
        'adr' : '354048',
        'protocol_version' : '1',
        'vertical_position' : '0',
        'status_map' : '0:OK',
        # Custom for variables
        'o2concentration_id' : '0',
        'o2concentration_description' : 'O2Concentration',
        'o2concentration_type' : 'VT_R4',
        'o2concentration_format' : '%0.3f',
        'o2concentration_units' : 'uM',
        'o2concentration_range_min' :'0',
        'o2concentration_range_max' : '500',
        'airsaturation_id' : '1',
        'airsaturation_description' : 'AirSaturation',
        'airsaturation_type' : 'VT_R4',
        'airsaturation_format' : '%0.3f',
        'airsaturation_units' : '%',
        'airsaturation_range_min' :'0',
        'airsaturation_range_max' : '150',
        'temperature_id' : '2',
        'temperature_description' : 'Temperature',
        'temperature_type' : 'VT_R4',
        'temperature_format' : '%0.3f',
        'temperature_units' : 'Deg.C',
        'temperature_range_min' :'0',
        'temperature_range_max' : '40',
        'calphase_id' : '3',
        'calphase_description' : 'CalPhase',
        'calphase_type' : 'VT_R4',
        'calphase_format' : '%0.3f',
        'calphase_units' : 'Deg',
        'calphase_range_min' :'0',
        'calphase_range_max' : '90',
        'tcphase_id' : '4',
        'tcphase_description' : 'TCPhase',
        'tcphase_type' : 'VT_R4',
        'tcphase_format' : '%0.3f',
        'tcphase_units' : 'Deg',
        'tcphase_range_min' :'0',
        'tcphase_range_max' : '90',
        'c1rph_id' : '5',
        'c1rph_description' : 'C1RPh',
        'c1rph_type' : 'VT_R4',
        'c1rph_format' : '%0.3f',
        'c1rph_units' : 'Deg',
        'c1rph_range_min' :'0',
        'c1rph_range_max' : '90',
        'c2rph_id' : '6',
        'c2rph_description' : 'C2RPh',
        'c2rph_type' : 'VT_R4',
        'c2rph_format' : '%0.3f',
        'c2rph_units' : 'Deg',
        'c2rph_range_min' :'0',
        'c2rph_range_max' : '90',
        'c1amp_id' : '7',
        'c1amp_description' : 'C1Amp',
        'c1amp_type' : 'VT_R4',
        'c1amp_format' : '%0.1f',
        'c1amp_units' : 'mV',
        'c1amp_range_min' :'0',
        'c1amp_range_max' : '3300',
        'c2amp_id' : '8',
        'c2amp_description' : 'C2Amp',
        'c2amp_type' : 'VT_R4',
        'c2amp_format' : '%0.1f',
        'c2amp_units' : 'mV',
        'c2amp_range_min' :'0',
        'c2amp_range_max' : '3300',
        'rawtemp_id' : '9',
        'rawtemp_description' : 'RawTemp',
        'rawtemp_type' : 'VT_R4',
        'rawtemp_format' : '%0.1f',
        'rawtemp_units' : 'mV',
        'rawtemp_range_min' :'0',
        'rawtemp_range_max' : '1500',
    },
    'optode_175' : { 'id' : 'optode_175',
        # Used by raw2proc
        'raw_dir' : '/seacoos/data/nccoos/level0/'
        'largo/mini_andi/xml',
        'raw_file_glob' : '*.xml',
        'proc_dir' : '/seacoos/data/nccoos/level1/'
        'largo/mini_andi/nc',
        'process_module' : 'proc_mini_andi_optode',
        'utc_offset' : 0,  # hours offset to utc
        'location' : 'Florida Keys National Marine Sanctuary',
        'lat' : 24.9500,   # degrees true (-) south, (+) north
        'lon' : -80.4536,  # degrees true (-) west, (+) east
        'mvar' : -5.6333,  # degrees (-) west, (+) east
        'elevation' : -20.0, # meters
        # Custom
        'id_number' : '4330F-175',
        'serial_number' : '175',
        'product_number' : '4330F',
        'product_name' : 'Optode Sensor',
        'description' : 'Optode Sensor 4330F#175',
        'adr' : '354560',
        'protocol_version' : '1',
        'vertical_position' : '0',
        'status_map' : '0:OK',
        # Custom for variables
        'o2concentration_id' : '0',
        'o2concentration_description' : 'O2Concentration',
        'o2concentration_type' : 'VT_R4',
        'o2concentration_format' : '%0.3f',
        'o2concentration_units' : 'uM',
        'o2concentration_range_min' :'0',
        'o2concentration_range_max' : '500',
        'airsaturation_id' : '1',
        'airsaturation_description' : 'AirSaturation',
        'airsaturation_type' : 'VT_R4',
        'airsaturation_format' : '%0.3f',
        'airsaturation_units' : '%',
        'airsaturation_range_min' :'0',
        'airsaturation_range_max' : '150',
        'temperature_id' : '2',
        'temperature_description' : 'Temperature',
        'temperature_type' : 'VT_R4',
        'temperature_format' : '%0.3f',
        'temperature_units' : 'Deg.C',
        'temperature_range_min' :'0',
        'temperature_range_max' : '40',
        'calphase_id' : '3',
        'calphase_description' : 'CalPhase',
        'calphase_type' : 'VT_R4',
        'calphase_format' : '%0.3f',
        'calphase_units' : 'Deg',
        'calphase_range_min' :'0',
        'calphase_range_max' : '90',
        'tcphase_id' : '4',
        'tcphase_description' : 'TCPhase',
        'tcphase_type' : 'VT_R4',
        'tcphase_format' : '%0.3f',
        'tcphase_units' : 'Deg',
        'tcphase_range_min' :'0',
        'tcphase_range_max' : '90',
        'c1rph_id' : '5',
        'c1rph_description' : 'C1RPh',
        'c1rph_type' : 'VT_R4',
        'c1rph_format' : '%0.3f',
        'c1rph_units' : 'Deg',
        'c1rph_range_min' :'0',
        'c1rph_range_max' : '90',
        'c2rph_id' : '6',
        'c2rph_description' : 'C2RPh',
        'c2rph_type' : 'VT_R4',
        'c2rph_format' : '%0.3f',
        'c2rph_units' : 'Deg',
        'c2rph_range_min' :'0',
        'c2rph_range_max' : '90',
        'c1amp_id' : '7',
        'c1amp_description' : 'C1Amp',
        'c1amp_type' : 'VT_R4',
        'c1amp_format' : '%0.1f',
        'c1amp_units' : 'mV',
        'c1amp_range_min' :'0',
        'c1amp_range_max' : '3300',
        'c2amp_id' : '8',
        'c2amp_description' : 'C2Amp',
        'c2amp_type' : 'VT_R4',
        'c2amp_format' : '%0.1f',
        'c2amp_units' : 'mV',
        'c2amp_range_min' :'0',
        'c2amp_range_max' : '3300',
        'rawtemp_id' : '9',
        'rawtemp_description' : 'RawTemp',
        'rawtemp_type' : 'VT_R4',
        'rawtemp_format' : '%0.1f',
        'rawtemp_units' : 'mV',
        'rawtemp_range_min' :'0',
        'rawtemp_range_max' : '1500',
    },
    'optode_176' : { 'id' : 'optode_176',
        # Used by raw2proc
        'raw_dir' : '/seacoos/data/nccoos/level0/'
        'largo/mini_andi/xml',
        'raw_file_glob' : '*.xml',
        'proc_dir' : '/seacoos/data/nccoos/level1/'
        'largo/mini_andi/nc',
        'process_module' : 'proc_mini_andi_optode',
        'utc_offset' : 0,  # hours offset to utc
        'location' : 'Florida Keys National Marine Sanctuary',
        'lat' : 24.9500,   # degrees true (-) south, (+) north
        'lon' : -80.4536,  # degrees true (-) west, (+) east
        'mvar' : -5.6333,  # degrees (-) west, (+) east
        'elevation' : -20.0, # meters
        # Custom
        'id_number' : '4330F-176',
        'serial_number' : '176',
        'product_number' : '4330F',
        'product_name' : 'Optode Sensor',
        'description' : 'Optode Sensor 4330F#176',
        'adr' : '354816',
        'protocol_version' : '1',
        'vertical_position' : '0',
        'status_map' : '0:OK',
        # Custom for variables
        'o2concentration_id' : '0',
        'o2concentration_description' : 'O2Concentration',
        'o2concentration_type' : 'VT_R4',
        'o2concentration_format' : '%0.3f',
        'o2concentration_units' : 'uM',
        'o2concentration_range_min' :'0',
        'o2concentration_range_max' : '500',
        'airsaturation_id' : '1',
        'airsaturation_description' : 'AirSaturation',
        'airsaturation_type' : 'VT_R4',
        'airsaturation_format' : '%0.3f',
        'airsaturation_units' : '%',
        'airsaturation_range_min' :'0',
        'airsaturation_range_max' : '150',
        'temperature_id' : '2',
        'temperature_description' : 'Temperature',
        'temperature_type' : 'VT_R4',
        'temperature_format' : '%0.3f',
        'temperature_units' : 'Deg.C',
        'temperature_range_min' :'0',
        'temperature_range_max' : '40',
        'calphase_id' : '3',
        'calphase_description' : 'CalPhase',
        'calphase_type' : 'VT_R4',
        'calphase_format' : '%0.3f',
        'calphase_units' : 'Deg',
        'calphase_range_min' :'0',
        'calphase_range_max' : '90',
        'tcphase_id' : '4',
        'tcphase_description' : 'TCPhase',
        'tcphase_type' : 'VT_R4',
        'tcphase_format' : '%0.3f',
        'tcphase_units' : 'Deg',
        'tcphase_range_min' :'0',
        'tcphase_range_max' : '90',
        'c1rph_id' : '5',
        'c1rph_description' : 'C1RPh',
        'c1rph_type' : 'VT_R4',
        'c1rph_format' : '%0.3f',
        'c1rph_units' : 'Deg',
        'c1rph_range_min' :'0',
        'c1rph_range_max' : '90',
        'c2rph_id' : '6',
        'c2rph_description' : 'C2RPh',
        'c2rph_type' : 'VT_R4',
        'c2rph_format' : '%0.3f',
        'c2rph_units' : 'Deg',
        'c2rph_range_min' :'0',
        'c2rph_range_max' : '90',
        'c1amp_id' : '7',
        'c1amp_description' : 'C1Amp',
        'c1amp_type' : 'VT_R4',
        'c1amp_format' : '%0.1f',
        'c1amp_units' : 'mV',
        'c1amp_range_min' :'0',
        'c1amp_range_max' : '3300',
        'c2amp_id' : '8',
        'c2amp_description' : 'C2Amp',
        'c2amp_type' : 'VT_R4',
        'c2amp_format' : '%0.1f',
        'c2amp_units' : 'mV',
        'c2amp_range_min' :'0',
        'c2amp_range_max' : '3300',
        'rawtemp_id' : '9',
        'rawtemp_description' : 'RawTemp',
        'rawtemp_type' : 'VT_R4',
        'rawtemp_format' : '%0.1f',
        'rawtemp_units' : 'mV',
        'rawtemp_range_min' :'0',
        'rawtemp_range_max' : '1500',
    },
    'optode_178' : { 'id' : 'optode_178',
        # Used by raw2proc
        'raw_dir' : '/seacoos/data/nccoos/level0/'
        'largo/mini_andi/xml',
        'raw_file_glob' : '*.xml',
        'proc_dir' : '/seacoos/data/nccoos/level1/'
        'largo/mini_andi/nc',
        'process_module' : 'proc_mini_andi_optode',
        'utc_offset' : 0,  # hours offset to utc
        'location' : 'Florida Keys National Marine Sanctuary',
        'lat' : 24.9500,   # degrees true (-) south, (+) north
        'lon' : -80.4536,  # degrees true (-) west, (+) east
        'mvar' : -5.6333,  # degrees (-) west, (+) east
        'elevation' : -20.0, # meters
        # Custom
        'id_number' : '4330F-178',
        'serial_number' : '178',
        'product_number' : '4330F',
        'product_name' : 'Optode Sensor',
        'description' : 'Optode Sensor 4330F#178',
        'adr' : '355328',
        'protocol_version' : '1',
        'vertical_position' : '0',
        'status_map' : '0:OK',
        # Custom for variables
        'o2concentration_id' : '0',
        'o2concentration_description' : 'O2Concentration',
        'o2concentration_type' : 'VT_R4',
        'o2concentration_format' : '%0.3f',
        'o2concentration_units' : 'uM',
        'o2concentration_range_min' :'0',
        'o2concentration_range_max' : '500',
        'airsaturation_id' : '1',
        'airsaturation_description' : 'AirSaturation',
        'airsaturation_type' : 'VT_R4',
        'airsaturation_format' : '%0.3f',
        'airsaturation_units' : '%',
        'airsaturation_range_min' :'0',
        'airsaturation_range_max' : '150',
        'temperature_id' : '2',
        'temperature_description' : 'Temperature',
        'temperature_type' : 'VT_R4',
        'temperature_format' : '%0.3f',
        'temperature_units' : 'Deg.C',
        'temperature_range_min' :'0',
        'temperature_range_max' : '40',
        'calphase_id' : '3',
        'calphase_description' : 'CalPhase',
        'calphase_type' : 'VT_R4',
        'calphase_format' : '%0.3f',
        'calphase_units' : 'Deg',
        'calphase_range_min' :'0',
        'calphase_range_max' : '90',
        'tcphase_id' : '4',
        'tcphase_description' : 'TCPhase',
        'tcphase_type' : 'VT_R4',
        'tcphase_format' : '%0.3f',
        'tcphase_units' : 'Deg',
        'tcphase_range_min' :'0',
        'tcphase_range_max' : '90',
        'c1rph_id' : '5',
        'c1rph_description' : 'C1RPh',
        'c1rph_type' : 'VT_R4',
        'c1rph_format' : '%0.3f',
        'c1rph_units' : 'Deg',
        'c1rph_range_min' :'0',
        'c1rph_range_max' : '90',
        'c2rph_id' : '6',
        'c2rph_description' : 'C2RPh',
        'c2rph_type' : 'VT_R4',
        'c2rph_format' : '%0.3f',
        'c2rph_units' : 'Deg',
        'c2rph_range_min' :'0',
        'c2rph_range_max' : '90',
        'c1amp_id' : '7',
        'c1amp_description' : 'C1Amp',
        'c1amp_type' : 'VT_R4',
        'c1amp_format' : '%0.1f',
        'c1amp_units' : 'mV',
        'c1amp_range_min' :'0',
        'c1amp_range_max' : '3300',
        'c2amp_id' : '8',
        'c2amp_description' : 'C2Amp',
        'c2amp_type' : 'VT_R4',
        'c2amp_format' : '%0.1f',
        'c2amp_units' : 'mV',
        'c2amp_range_min' :'0',
        'c2amp_range_max' : '3300',
        'rawtemp_id' : '9',
        'rawtemp_description' : 'RawTemp',
        'rawtemp_type' : 'VT_R4',
        'rawtemp_format' : '%0.1f',
        'rawtemp_units' : 'mV',
        'rawtemp_range_min' :'0',
        'rawtemp_range_max' : '1500',
    },
    'optode_179' : { 'id' : 'optode_179',
        # Used by raw2proc
        'raw_dir' : '/seacoos/data/nccoos/level0/'
        'largo/mini_andi/xml',
        'raw_file_glob' : '*.xml',
        'proc_dir' : '/seacoos/data/nccoos/level1/'
        'largo/mini_andi/nc',
        'process_module' : 'proc_mini_andi_optode',
        'utc_offset' : 0,  # hours offset to utc
        'location' : 'Florida Keys National Marine Sanctuary',
        'lat' : 24.9500,   # degrees true (-) south, (+) north
        'lon' : -80.4536,  # degrees true (-) west, (+) east
        'mvar' : -5.6333,  # degrees (-) west, (+) east
        'elevation' : -20.0, # meters
        # Custom
        'id_number' : '4330F-179',
        'serial_number' : '179',
        'product_number' : '4330F',
        'product_name' : 'Optode Sensor',
        'description' : 'Optode Sensor 4330F#179',
        'adr' : '355584',
        'protocol_version' : '1',
        'vertical_position' : '0',
        'status_map' : '0:OK',
        # Custom for variables
        'o2concentration_id' : '0',
        'o2concentration_description' : 'O2Concentration',
        'o2concentration_type' : 'VT_R4',
        'o2concentration_format' : '%0.3f',
        'o2concentration_units' : 'uM',
        'o2concentration_range_min' :'0',
        'o2concentration_range_max' : '500',
        'airsaturation_id' : '1',
        'airsaturation_description' : 'AirSaturation',
        'airsaturation_type' : 'VT_R4',
        'airsaturation_format' : '%0.3f',
        'airsaturation_units' : '%',
        'airsaturation_range_min' :'0',
        'airsaturation_range_max' : '150',
        'temperature_id' : '2',
        'temperature_description' : 'Temperature',
        'temperature_type' : 'VT_R4',
        'temperature_format' : '%0.3f',
        'temperature_units' : 'Deg.C',
        'temperature_range_min' :'0',
        'temperature_range_max' : '40',
        'calphase_id' : '3',
        'calphase_description' : 'CalPhase',
        'calphase_type' : 'VT_R4',
        'calphase_format' : '%0.3f',
        'calphase_units' : 'Deg',
        'calphase_range_min' :'0',
        'calphase_range_max' : '90',
        'tcphase_id' : '4',
        'tcphase_description' : 'TCPhase',
        'tcphase_type' : 'VT_R4',
        'tcphase_format' : '%0.3f',
        'tcphase_units' : 'Deg',
        'tcphase_range_min' :'0',
        'tcphase_range_max' : '90',
        'c1rph_id' : '5',
        'c1rph_description' : 'C1RPh',
        'c1rph_type' : 'VT_R4',
        'c1rph_format' : '%0.3f',
        'c1rph_units' : 'Deg',
        'c1rph_range_min' :'0',
        'c1rph_range_max' : '90',
        'c2rph_id' : '6',
        'c2rph_description' : 'C2RPh',
        'c2rph_type' : 'VT_R4',
        'c2rph_format' : '%0.3f',
        'c2rph_units' : 'Deg',
        'c2rph_range_min' :'0',
        'c2rph_range_max' : '90',
        'c1amp_id' : '7',
        'c1amp_description' : 'C1Amp',
        'c1amp_type' : 'VT_R4',
        'c1amp_format' : '%0.1f',
        'c1amp_units' : 'mV',
        'c1amp_range_min' :'0',
        'c1amp_range_max' : '3300',
        'c2amp_id' : '8',
        'c2amp_description' : 'C2Amp',
        'c2amp_type' : 'VT_R4',
        'c2amp_format' : '%0.1f',
        'c2amp_units' : 'mV',
        'c2amp_range_min' :'0',
        'c2amp_range_max' : '3300',
        'rawtemp_id' : '9',
        'rawtemp_description' : 'RawTemp',
        'rawtemp_type' : 'VT_R4',
        'rawtemp_format' : '%0.1f',
        'rawtemp_units' : 'mV',
        'rawtemp_range_min' :'0',
        'rawtemp_range_max' : '1500',
    },
    'conductivity' : { 'id' : 'conductivity',
        # Used by raw2proc
        'raw_dir' : '/seacoos/data/nccoos/level0/'
        'largo/mini_andi/xml',
        'raw_file_glob' : '*.xml',
        'proc_dir' : '/seacoos/data/nccoos/level1/'
        'largo/mini_andi/nc',
        'process_module' : 'proc_mini_andi_conductivity',
        'utc_offset' : 0,  # hours offset to utc
        'location' : 'Florida Keys National Marine Sanctuary',
        'lat' : 24.9500,   # degrees true (-) south, (+) north
        'lon' : -80.4536,  # degrees true (-) west, (+) east
        'mvar' : -5.6333,  # degrees (-) west, (+) east
        'elevation' : -20.0, # meters
        # Custom
        'id_number' : '4319-217',
        'serial_number' : '217',
        'product_number' : '4319',
        'product_name' : 'Conductivity Sensor',
        'description' : 'Conductivity #217',
        'adr' : '362752',
        'protocol_version' : '1',
        'vertical_position' : '0',
        'status_map' : '0:OK',
        # Custom for variables
        'conductivity_id' : '0',
        'conductivity_description' : 'Conductivity',
        'conductivity_type' : 'VT_R4',
        'conductivity_format' : '%0.3f',
        'conductivity_units' : 'mS/cm',
        'conductivity_range_min' :'0',
        'conductivity_range_max' : '75',
        'temperature_id' : '1',
        'temperature_description' : 'Temperature',
        'temperature_type' : 'VT_R4',
        'temperature_format' : '%0.3f',
        'temperature_units' : 'Deg.C',
        'temperature_range_min' :'-5',
        'temperature_range_max' : '35',
    },
    'pressure' : { 'id' : 'pressure',
        # Used by raw2proc
        'raw_dir' : '/seacoos/data/nccoos/level0/'
        'largo/mini_andi/xml',
        'raw_file_glob' : '*.xml',
        'proc_dir' : '/seacoos/data/nccoos/level1/'
        'largo/mini_andi/nc',
        'process_module' : 'proc_mini_andi_pressure',
        'utc_offset' : 0,  # hours offset to utc
        'location' : 'Florida Keys National Marine Sanctuary',
        'lat' : 24.9500,   # degrees true (-) south, (+) north
        'lon' : -80.4536,  # degrees true (-) west, (+) east
        'mvar' : -5.6333,  # degrees (-) west, (+) east
        'elevation' : -20.0, # meters
        # Custom
        'id_number' : '4117D-235',
        'serial_number' : '235',
        'product_number' : '4117D',
        'product_name' : 'Pressure Sensor',
        'description' : 'Pressure #235',
        'adr' : '366848',
        'protocol_version' : '1',
        'vertical_position' : '0',
        'status_map' : '0:OK',
        # Custom for variables
        'pressure_id' : '0',
        'pressure_description' : 'Pressure',
        'pressure_type' : 'VT_R4',
        'pressure_format' : '%0.3f',
        'pressure_units' : 'kPa',
        'pressure_range_min' :'0',
        'pressure_range_max' : '1000',
        'temperature_id' : '1',
        'temperature_description' : 'Temperature',
        'temperature_type' : 'VT_R4',
        'temperature_format' : '%0.3f',
        'temperature_units' : 'DegC',
        'temperature_range_min' :'-5',
        'temperature_range_max' : '35',
    },
    'current' : { 'id' : 'current',
        # Used by raw2proc
        'raw_dir' : '/seacoos/data/nccoos/level0/'
        'largo/mini_andi/xml',
        'raw_file_glob' : '*.xml',
        'proc_dir' : '/seacoos/data/nccoos/level1/'
        'largo/mini_andi/nc',
        'process_module' : 'proc_mini_andi_current',
        'utc_offset' : 0,  # hours offset to utc
        'location' : 'Florida Keys National Marine Sanctuary',
        'lat' : 24.9500,   # degrees true (-) south, (+) north
        'lon' : -80.4536,  # degrees true (-) west, (+) east
        'mvar' : -5.6333,  # degrees (-) west, (+) east
        'elevation' : -20.0, # meters
        # Custom
        'id_number' : '4520-275',
        'serial_number' : '275',
        'product_number' : '4520',
        'product_name' : 'Doppler Current Sensor',
        'description' : 'DCS #275',
        'adr' : '591360',
        'protocol_version' : '1',
        'vertical_position' : '0',
        'status_map' : '0:OK',
        # Custom for variables
        'abs_speed_id' : '0',
        'abs_speed_description' : 'Abs Speed',
        'abs_speed_type' : 'VT_R4',
        'abs_speed_format' : '%0.3f',
        'abs_speed_units' : 'cm/s',
        'abs_speed_range_min' :'0',
        'abs_speed_range_max' : '300',
        'direction_id' : '1',
        'direction_description' : 'Direction',
        'direction_type' : 'VT_R4',
        'direction_format' : '%0.3f',
        'direction_units' : 'Deg.M',
        'direction_range_min' :'0',
        'direction_range_max' : '360',
        'v_id' : '2',
        'v_description' : 'North',
        'v_type' : 'VT_R4',
        'v_format' : '%0.3f',
        'v_units' : 'cm/s',
        'v_range_min' :'-300',
        'v_range_max' : '300',
        'u_id' : '3',
        'u_description' : 'East',
        'u_type' : 'VT_R4',
        'u_format' : '%0.3f',
        'u_units' : 'cm/s',
        'u_range_min' :'-300',
        'u_range_max' : '300',
        'heading_id' : '4',
        'heading_description' : 'Heading',
        'heading_type' : 'VT_R4',
        'heading_format' : '%0.3f',
        'heading_units' : 'Deg.M',
        'heading_range_min' :'0',
        'heading_range_max' : '360',
        'tiltx_id' : '5',
        'tiltx_description' : 'Tilt X',
        'tiltx_type' : 'VT_R4',
        'tiltx_format' : '%0.3f',
        'tiltx_units' : 'Deg',
        'tiltx_range_min' :'-45',
        'tiltx_range_max' : '45',
        'tilty_id' : '6',
        'tilty_description' : 'Tilt Y',
        'tilty_type' : 'VT_R4',
        'tilty_format' : '%0.3f',
        'tilty_units' : 'Deg',
        'tilty_range_min' :'-45',
        'tilty_range_max' : '45',
        'std_speed_id' : '7',
        'std_speed_description' : 'SP Std',
        'std_speed_type' : 'VT_R4',
        'std_speed_format' : '%0.3f',
        'std_speed_units' : 'cm/s',
        'std_speed_range_min' :'0',
        'std_speed_range_max' : '20',
        'strength_id' : '8',
        'strength_description' : 'Strength',
        'strength_type' : 'VT_R4',
        'strength_format' : '%0.3f',
        'strength_units' : 'dB',
        'strength_range_min' : '-80',
        'strength_range_max' : '0',
        'pings_id' : '9',
        'pings_description' : 'Ping Count',
        'pings_type' : 'VT_12',
        'pings_format' : '%d',
        'pings_units' : '',
        'pings_range_min' :'',
        'pings_range_max' : '',
    },
}
