template = {
    'param' : {'min' : None,
               'max' : None,
               'accuracy' : None,
               'resolution' : ,
               'units' : '',
               },
    }

rdi_workhorse = {
    'time' : {'resolution' : 0.01,
               'units' : 'sec',
               },
    'velocity' : {'min' : -20.,
                  'max' : 20.,
                  'accuracy' : 0.003,
                  'resolution' : 0.001,
                  'units' : 'm s-1',
                  },
    'temperature' : {'min' : -5.,
                     'max' : 40.,
                     'accuracy' : 0.4,
                     'resolution' : -.1,
                     'units' : 'degrees_celsius',
                     },
    'heading' : {'min' : 0.,
               'max' : 360.,
               'accuracy' : 2.,
               'resolution' : 0.01,
               'units' : 'degrees',
               },
    'pitch' : {'min' : -20.,
               'max' : 20.,
               'accuracy' : 1.,
               'resolution' : 0.01,
               'units' : 'degrees',
               },
    'roll' : {'min' : -20.,
               'max' : 20.,
               'accuracy' : 1.,
               'resolution' : 0.01,
               'units' : 'degrees',
               },    
    'voltage_input' : {'min' : 20.,
                       'max' : 50.,
                       'accuracy' : 0.1,
                       'resolution' : 0.1,
                       'units' : 'volts',
                       },
    'correlation_magnitude' : {'min' : 0,
               'max' : 255,
               'units' : None,
               },
    'echo_intensity' : {'min' : 0,
               'max' : 255,
               'units' : None,
               },
    'percent_good' : {'min' : 0,
               'max' : 100,
               'units' : '%',
               },

    }

rdi_workhorse_waves = {}


